version: 2.1
orbs:
  cypress: cypress-io/cypress@6.1.0 # https://github.com/cypress-io/circleci-orb/releases
  browser-tools: circleci/browser-tools@2.4.2 # https://circleci.com/developer/orbs/orb/circleci/browser-tools

jobs:

  linux-test-chrome:
    executor:
      name: cypress/default
      node-version: '24.20.0'
    steps:
      - browser-tools/install_chrome
      - cypress/install
      - run:
          name: Run Cypress
          command: 'npx cypress run --browser chrome'
          no_output_timeout: 5m

workflows:
  linux-build:
    jobs:
      - linux-test-chrome:
          name: linux-test-chrome-1
      - linux-test-chrome:
          name: linux-test-chrome-2
      - linux-test-chrome:
          name: linux-test-chrome-3
      - linux-test-chrome:
          name: linux-test-chrome-4
      - linux-test-chrome:
          name: linux-test-chrome-5
