version: 2.1
orbs:
  cypress: cypress-io/cypress@6.1.0 # https://github.com/cypress-io/circleci-orb/releases
  browser-tools: circleci/browser-tools@2.4.2 # https://circleci.com/developer/orbs/orb/circleci/browser-tools

jobs:

  linux-test-chrome:
    executor:
      name: cypress/default
      node-version: '24.20.0'
    steps:
      - browser-tools/install_chrome
      - cypress/install
      - run:
          name: Run Cypress
          command: 'npx cypress run --browser chrome'
          no_output_timeout: 5m

  docker-browsers-test-chrome:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress
          command: 'npx cypress run --browser chrome'
          no_output_timeout: 5m

workflows:
  linux-orb-build:
    jobs:
      - linux-test-chrome:
          name: linux-test-chrome-1
      - linux-test-chrome:
          name: linux-test-chrome-2
      - linux-test-chrome:
          name: linux-test-chrome-3
      - linux-test-chrome:
          name: linux-test-chrome-4
      - linux-test-chrome:
          name: linux-test-chrome-5
      - linux-test-chrome:
          name: linux-test-chrome-6
          requires:
            - linux-test-chrome-5
      - linux-test-chrome:
          name: linux-test-chrome-7
          requires:
            - linux-test-chrome-6
      - linux-test-chrome:
          name: linux-test-chrome-8
          requires:
            - linux-test-chrome-7
      - linux-test-chrome:
          name: linux-test-chrome-9
          requires:
            - linux-test-chrome-8
      - linux-test-chrome:
          name: linux-test-chrome-10
          requires:
            - linux-test-chrome-9

  linux-docker-build:
    jobs:
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-1
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-2
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-3
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-4
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-5
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-6
          requires:
            - docker-browsers-test-chrome-5
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-7
          requires:
            - docker-browsers-test-chrome-6
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-8
          requires:
            - docker-browsers-test-chrome-7
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-9
          requires:
            - docker-browsers-test-chrome-8
      - docker-browsers-test-chrome:
          name: docker-browsers-test-chrome-10
          requires:
            - docker-browsers-test-chrome-9
