name: Cypress Test with action

on:
  workflow_dispatch:

env:
  DEBUG: '@cypress/github-action'
  NO_COLOR: true

jobs:
  Cypress-Test-options:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show default Node.js
        run: node -v

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Show selected Node.js
        run: node --version; npm --version; which -a node; echo $PATH

      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: node -v
          build: node -v
          start: node -v

  Cypress-Test-with-action:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show default Node.js
        run: node -v

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Show selected Node.js
        run: node --version; npm --version; which -a node; echo $PATH

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: node -v
