name: Cypress Test native
on:
  workflow_dispatch:

jobs:
  Cypress-Test-native:
    runs-on: ubuntu-22.04
    env:
      NO_COLOR: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'

      - name: npm install
        run: npm ci

      - name: Cypress run
        run: npx cypress run -s cypress/e2e/spec.cy.js 
