name: example-firefox
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  firefox:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Firefox run multiple times
        run: |
          for i in {1..10}
          do
            npx cypress run -b firefox
          done
