name: example-firefox
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  firefox:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Firefox run multiple times
        run: |
          for i in {1..10}
          do
            npx cypress run -s cypress/e2e/spec.cy.js -b firefox
          done
        env:
          DEBUG: cypress:server:profilecleaner
